using Content.Client._SpaceDream.SpeechBarks.Systems;
using Content.Shared._SpaceDream.SpeechBarks.Prototypes;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Random;

namespace Content.Client._SpaceDream.SpeechBarks.UI.CharacterEditor;

[GenerateTypedNameReferences]
public sealed partial class SpeechBarkPicker : BoxContainer
{
    [Dependency] private IPrototypeManager _proto = default!;
    [Dependency] private IEntityManager _entManager = default!;
    [Dependency] private IRobustRandom _random = default!;

    private const int AutoBarkId = 0;
    private readonly List<BarkPrototype> _barks = new();
    private SpeechBarksSystem _barksSystem = default!;
    private bool _updating;

    public event Action<ProtoId<BarkPrototype>?>? OnBarkSelected;

    public SpeechBarkPicker()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _barksSystem = _entManager.System<SpeechBarksSystem>();

        PopulateBarks();
        BarkDropdown.OnItemSelected += OnDropdownItemSelected;
        PreviewButton.OnPressed += _ => PlayPreview();
    }

    public void SetProfile(HumanoidCharacterProfile? profile)
    {
        _updating = true;

        if (profile?.Voice == null)
        {
            BarkDropdown.SelectId(AutoBarkId);
            PreviewButton.Disabled = _barks.Count == 0;
            _updating = false;
            return;
        }

        var index = _barks.FindIndex(bark => bark.ID == profile.Voice.Value.Id);
        if (index < 0)
        {
            BarkDropdown.SelectId(AutoBarkId);
            PreviewButton.Disabled = _barks.Count == 0;
            _updating = false;
            return;
        }

        BarkDropdown.SelectId(index + 1);
        PreviewButton.Disabled = false;
        _updating = false;
    }

    private void PopulateBarks()
    {
        _barks.Clear();
        foreach (var bark in _proto.EnumeratePrototypes<BarkPrototype>())
        {
            if (bark.RoundStart)
                _barks.Add(bark);
        }

        _barks.Sort((a, b) => string.Compare(
            Loc.GetString(a.Name),
            Loc.GetString(b.Name),
            StringComparison.CurrentCultureIgnoreCase));

        BarkDropdown.Clear();
        BarkDropdown.AddItem(Loc.GetString("speech-bark-picker-auto"), AutoBarkId);

        for (var i = 0; i < _barks.Count; i++)
            BarkDropdown.AddItem(GetBarkDisplayName(_barks[i]), i + 1);

        BarkDropdown.SelectId(AutoBarkId);
        PreviewButton.Disabled = _barks.Count == 0;
    }

    private string GetBarkDisplayName(BarkPrototype bark)
    {
        return Loc.GetString(bark.Name);
    }

    private void OnDropdownItemSelected(OptionButton.ItemSelectedEventArgs args)
    {
        BarkDropdown.SelectId(args.Id);
        PreviewButton.Disabled = _barks.Count == 0;

        if (_updating)
            return;

        OnBarkSelected?.Invoke(args.Id == AutoBarkId ? null : _barks[args.Id - 1].ID);
    }

    private void PlayPreview()
    {
        if (_barks.Count == 0)
            return;

        var id = BarkDropdown.SelectedId;
        if (id != AutoBarkId && id - 1 >= _barks.Count)
            return;

        var bark = id == AutoBarkId
            ? _random.Pick(_barks)
            : _barks[id - 1];

        _barksSystem.PlayLocalPreview(bark);
    }
}
